# defines all app containers which docker compose will handle
services:
    # container name and hostname used by other services within the internal network
    api:
        # build image from Dockerfile instead of Docker Hub
        build:
            context: . # dockerfile is in this directory
            target: development # targets "development" stage build in multi-stage Dockerfile
        # maps machine port to container port
        ports:
            - 5000:5000
        # environment variables injected into the container
        environment:
            - NODE_ENV=development
            - PORT=5000
            - DATABASE_URL=${DATABASE_URL}
            - FRONTEND_URL=http://localhost:3000
            - BACKEND_URL=http://localhost:5000
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
            - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
            - BETTER_AUTH_URL=${BETTER_AUTH_URL}
        # sync local directory with container directory for hot reloading
        volumes:
            - .:/app
            - /app/node_modules # but node_modules is ignored in hot reloading so might need to rebuild Docker image when needed
        # docker will wait for postgres to be available before starting
        depends_on:
            postgres:
                condition: service_healthy
            migrate:
                condition: service_completed_successfully

    postgres:
        image: postgres:17-alpine
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - 5432:5432
        # persist data
        volumes:
            - postgres_data:/var/lib/postgresql/data
        # defines how Docker should check if postgres is healthy/ready
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 10s
            timeout: 5s
            retries: 5
    migrate:
        build:
            context: .
            target: development
        command: pnpm drizzle-kit push
        environment:
            - NODE_ENV=development
            - DATABASE_URL=${DATABASE_URL}
        volumes:
            - .:/app
            - /app/node_modules
        depends_on:
            postgres:
                condition: service_healthy

volumes:
    postgres_data:
